version: '3.8'

services:
  tubb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tubb-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Uncomment below if you need to persist logs
    # volumes:
    #   - ./logs:/app/logs
    networks:
      - tubb-network

networks:
  tubb-network:
    driver: bridge 